name: Publish Extension

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      publishToMarketplace:
        description: 'Publish to VS Code Marketplace'
        required: true
        default: 'true'
        type: boolean
      publishToOpenVSX:
        description: 'Publish to Open VSX Registry'
        required: true
        default: 'true'
        type: boolean

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Compile
      run: npm run compile
      
    - name: Run tests
      run: npm test
      
    - name: Package extension
      run: npm run package
      
    - name: Publish to VS Code Marketplace
      if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.publishToMarketplace == 'true')
      run: npm run publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
        
    - name: Publish to Open VSX Registry
      if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.publishToOpenVSX == 'true')
      run: npm run publish:openvsx
      env:
        OVSX_PAT: ${{ secrets.OVSX_PAT }}
        
    - name: Upload VSIX as artifact
      uses: actions/upload-artifact@v4
      with:
        name: vsix-package
        path: "*.vsix"
